* Towards EmacsListen
Consolidating information on using voice control for Emacs.

** Purpose
Emacs, with its hackability and wide range of application, has the
potential to be the ultimate environment for voice controlled
computing.

Unfortunately, information and tools aiming to take us closer to this
goal is fragmented and oftentimes hidden away in small repositories.
This makes it hard to get running with a good setup, as getting a lay
of the land is difficult.

This repository aims to be a centralized hub consolidating information
on how one can configure Emacs to be the perfect voice controlled
environment to accomplish one's computing goals.  This ideal of Emacs
as a voice controlled environment for all computing tasks is dubbed
EmacsListen, in homage to Emacspeak, a project that made Emacs into an
audio oriented computing environment.

** Current State
Right now, this research document should should accumulate all
information accessible on the internet for setting up Emacs as a voice
controlled environment.  At this stage, we try to collect an index of
the tools available.  For this reason, this document may just look
like a list of links at the start.  From this, a proper "EmacsListen
canon" will be selected.

The hope is that with time, this document evolves into a guide that
can get a person running with voice control in a reasonable amount of
time.  It should also be a hub of information for the voice control
hacker to find what already exist, enabling better cooperation to
develop a more powerful environment.

** Desiderata for EmacsListen
- Hackability: Hacking on the voice control system should be as
  comfortable and powerful as hacking on any other Emacs feature or
  configuration.  Creating ad-hoc solutions to new situations should
  be easy.
- Good citizen: As far as possible, interplay with the existing
  faculties of Emacs as nicely as possible.  For example, if voice
  commands can be made into command loop input events, this is
  preferable to having a parallel system for voice input.  In this
  way, old functionality can more easily be leveraged for voice
  control.
- Free (as in freedom): Ideally, no proprietary components would be
  required to get a good voice control experience.  If it is not
  currently possible, be mindful in designing the components in a way
  that would make it easy to switch out the proprietary components
  should the possibility arise.
- Input agnostic: While EmacsListen optimizes for voice control, try
  to design the systems in a way that still would make them amenable
  for alternative input modalities.  Having a unified interface across
  modalities lowers the cognitive load when switching between them.
- Documented: A motivated person with some computer experience should
  be able to figure out how to achieve their goals in EmacsListen
  without having to dig into the code or ask for help in forums.

*** Technical desiderata
- Ability to specify the language through a formal grammar.  This
  formal grammar should increase precision by restricting what er thus
  beach recognition recognizes.
- Ability to have dynamic grammars depending on the current
  state.  This is analogous to how different keymaps are available
  depending on the state of Emacs.
- Ability to specify the grammar completely from Emacs.

** Index
If you think something is missing from here, please open an issue or
pull request!

*** TODO Write descriptions for all the tools.

*** Voice Control Backends
- https://numenvoice.org/
  - Does not seem to allow grammars, just individual commands.
- https://kaldi-asr.org/doc/about.html
- https://github.com/daanzu/kaldi-active-grammar
- https://serenade.ai/
- https://cmusphinx.github.io/
- https://github.com/openai/whisper

**** Proprietary Backends
- https://talonvoice.com
- https://utterlyvoice.com/
- https://www.nuance.com/dragon.html

**** TODO Write distilled comparison between the backends

*** Generic Packages
These packages improve the voice control environment independently
of which backend is picked.

- https://github.com/ErikPrantare/hatty.el
- https://github.com/ErikPrantare/cursorfree.el
- https://github.com/jcaw/voicemacs/
  - Performs commands by creating a new input event type.  This
    approach is an example of being a good citizen: By putting the
    speech events into the command loop, things like undo boundaries
    and keyboard macros automatically work as expected.

*** Backend Specific Packages
- https://github.com/lepisma/emacs-speech-input (It seems
  they aim this to be backend-agnostic eventually)

**** Talon
- https://github.com/ErikPrantare/talon-list.el
- https://github.com/talonhub/community/tree/main/apps/emacs (Part of
  the community repository for talon)
- https://github.com/jcaw/talonscript-mode

**** Serenade
- https://github.com/justin-roche/serenade-mode

**** CMU Sphinx
- https://github.com/cwebber/emacslisten

**** Whisper
- https://github.com/natrys/whisper.el
